[project]
name = "diagnosis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "seaborn>=0.13.2",
    "tabulate>=0.9.0",
    "jupyter>=1.1.1",
    "ipykernel>=6.30.1",
    "scikit-learn>=1.7.1",
]
